service: serverless-demo
app: serverless-demo
org: innovationit


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  environment:
    CONTACTS_TABLE_NAME: contacts-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: 
      - Fn::GetAtt: [ contactsTable, Arn ]

functions:
  createContact:
    handler: createContact.handler
    events:
      - http:
          path: contacts
          method: post
  listContact:
    handler: listContact.handler
    events:
      - http:
          path: contacts
          method: get

resources:
 Resources:
  contactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.CONTACTS_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

